### ISSUE TITLE
retentionCount - what is it?

### ISSUE THREAD

**Issue by barbosacisco** [xninjaxelitex/nexus3-cleanup-release-artifact#3]
Hello, 

I am new to Nexus 3 and to Groovy, I did not understand what the variable retentionCount is for. Would you please clarify it for me? Thanks a lot!

Also, thanks very much for this script it works really good.

**Comment by ninjaxelite** [comment]
Hi barbosacisco,

the **retentionCount** is set to specify how many components you want to remain in your repository.
If retentionCount is 10 means -> delete until 10 components remains in the repository.

**Comment by barbosacisco** [comment]
Thanks a lot for the response! Now I got it.

**Comment by TejaswiniTharigopula2295** [comment]
Hello
I'm to new nexus, Could you please help me on how to execute this script against nexus repository
