### ISSUE TITLE
Script Execution

### ISSUE THREAD

**Issue by TejaswiniTharigopula2295** [xninjaxelitex/nexus3-cleanup-release-artifact#5]
Hello
Can you please help me on how to execute this script against nexus
It would be better if you include that in Readme.md file

Thanks in Advance

**Comment by ninjaxelite** [comment]
You could follow this link: https://support.sonatype.com/hc/en-us/articles/115015812727-Nexus-3-Groovy-Script-development-environment-setup

**Comment by TejaswiniTharigopula2295** [comment]
Also I need to delete particular components with name some xxx , can you help me on that

**Comment by ninjaxelite** [comment]
> Also I need to delete particular components with name some xxx , can you help me on that

Please open a new issue.
